import matplotlib.pyplot as plt
import numpy as np

#grid
fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111)
plt.xlabel("t")
plt.ylabel("S")
plt.xlim(0,100)
plt.ylim(0,100)
plt.grid()
plt.locator_params(axis='y', nbins=10)
plt.locator_params(axis='x', nbins=10)
ax.tick_params(axis='x', colors='white')
ax.tick_params(axis='y', colors='white')
plt.show()

#implicit
fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111)
plt.xlabel("t")
plt.ylabel("S")
plt.xlim(0,100)
plt.ylim(0,100)
plt.grid()
plt.locator_params(axis='y', nbins=10)
plt.locator_params(axis='x', nbins=10)
ax.tick_params(axis='x', colors='white')
ax.tick_params(axis='y', colors='white')
plt.plot(50,50,'bo')
plt.plot(40,40,'ro')
plt.plot(40,50,'ro') 
plt.plot(40,60,'ro') 
plt.show()

#explicit
fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111)
plt.xlabel("t")
plt.ylabel("S")
plt.xlim(0,100)
plt.ylim(0,100)
plt.grid()
plt.locator_params(axis='y', nbins=10)
plt.locator_params(axis='x', nbins=10)
ax.tick_params(axis='x', colors='white')
ax.tick_params(axis='y', colors='white')
plt.plot(50,50,'bo')
plt.plot(60,40,'ro')
plt.plot(60,50,'ro') 
plt.plot(60,60,'ro') 
plt.show()